baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Davis Builds Robots'
theme = 'PaperMod'

[permalinks]
  projects = "/projects/:slug/"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
